* Getting started
  Gather 'round on your favorite modern device and visit
  http://storychat.herokuapp.com/play

  Everyone should set their name (on the bottom right) to something that
  identifies them, so we can keep track of who's around. If you want to chat,
  switch your input type to "ooc" and type away.
* Tokens
  Every player starts off with 10 tokens. Tokens can be spent on buying
  characters, adding details to characters, and adding details to sets. They
  can also be used (through auction) to buy the privilege to frame the next
  scene (which is simply providing a slug line, a scene heading, and an idea
  that may or may not be followed by others).
* Choosing characters
  Enough characters should be created for all players to play at least
  one. There should also be a couple of side-characters that may be assigned to
  miscellaneous people who may not have speaking roles, necessarily.

  Players should visit http://storychat.herokuapp.com/characters and read
  through the various descriptions. There should be enough characters/roles for
  everyone to get started. Have them pick which ones they want.

  There should be two kinds of characters -- main characters and side
  characters. Main characters have longer descriptions and are meant for more
  important roles. Side characters have very terse descriptions and cannot be
  expanded in the future. They also cannot establish relationship links with
  other characters. They are essentially utility extras -- cashiers, bouncers,
  someone in a cubicle, a mom that says hi and is never seen again.

  Once players know what characters they want, they should decide how to
  allocate their tokens. A side character costs one token. A main character
  costs 3 tokens. Every player must have at least one main character. New
  characters may be created and purchased for the price of their initial
  cost. Main characters start with 2 details, side characters with one.

  Players may modify main characters with a single detail for one token (a
  very brief description of something about them -- a brief explanation of
  their outfit, a detail about their purple eyes, a compliment about their
  smile). A side character may be upgraded to a main character for 3 tokens,
  which also affords the player a single extra detail (the detail is
  obligatory, and the other two tokens go to upgrading the character so it can
  actually do more per scene)
* Sets
  New sets can be bought for 5 tokens. Money for sets can be pooled by
  players, but ownership is given to a single player. That player can also
  decide to add additional details to a set for 1 token apiece. A detail on a
  set is something like a prop that is placed somewhere, a description of the
  floor, and such. Every set gets 3 details as part of its purchase price, but
  all sets must have at least those 3 details (5 tokens is the minimum price).
* Scenes
  Once everyone's settled with their characters, a scene should be framed. A
  scene is a unit of drama that takes place in a single "set". This unit of
  drama should generally involve a single goal to be achieved -- that goal
  could be to expose something about the plot or a character, to introduce
  something new, or to actually resolve a plot point. Scenes shouldn't be too
  long (a few pages' worth of text is generally a good rule of thumb), and
  action should be fairly focused on the task at hand.

  A scene is marked by a slug line -- which is determined by the chosen set +
  time of day. Following the slug line is a scene header, which should be the
  description of the set, with all the details added to it, followed by a brief
  summary of what characters are in the scene when it starts, and where in the
  set they are.

  Once the scene is framed by the heading, players should play out the action
  in the scene until it draws to a close. Players can do anything they want,
  but any player can veto any particular part of the drama at any time, for any
  reason. If a veto happens, players should discuss what an alternative might
  be, which might end up with the vetoed action being brought back in a
  different way, or just the same as it was before. If disagreement becomes
  disruptive, players can decide to end the scene and try something
  different. Players who leave can choose to cancel the scene altogether
  (because they don't like the role their character has taken in it), or allow
  the scene to continue without their character, letting others finish up. As a
  general rule, all players should be considerate about each others' feelings
  and vetoes should not be done, or taken, lightly. A veto is a potentially
  scene-canceling action, but its purpose is to make sure no one is terribly
  unhappy with the results of a cooperatively-played scene. Be amicable when
  resolving veto-related issues.

  Scenes are played out by players using a character to add either dia
  Once the scene draws to a close, players discuss the next step, repick
  characters, etc.
* Awards
  Each player involved in a scene has two tokens to give out: One for the player
  who played their character the best (maybe they led the scene in an excellent
  way, or they really nailed a plot point, or they were excellent supports to a
  central character, or just generally brought life to a scene, regardless of
  their starring status), and one for the player who players themselves enjoyed
  interacting with the most. Maybe they were gracious and patient when something
  wasn't going well, or they helped someone out with a good idea. Tokens cannot
  be given to oneself, and players are not obligated to give away both of their
  tokens if they don't feel anyone was particularly great.

  (Note: In the future, token-giving should be blind and anonymous -- no one
  knows who's received the most tokens, and no one knows who gave tokens to
  whom)

  The player who ends up with the most tokens receives additional tokens equal
  to the total number of players in the scene.
* Story arcs
  As scenes are played out, players should organize them into story arcs, in
  whatever order they see fit. These story arcs should tell a larger story than
  what each individual scene does. Scenes in a story arc are ordered
  linearly. There can be multiple story arcs running in parallel, and multiple
  story arcs can use the same scene, if necessary. It's generally helpful to
  have some kind of plan/cohesion to story arcs, and they can be very useful in
  planning future scenes.

  Story arcs can also be 'tokened' by players other than the story arc
  manager. Every token given to a story arc is given to the player managing
  that story arc. Any player can token any story arc other than their own, and
  they can token as many as they want.
* Spending tokens
  Tokens can be spent between scenes to add details to characters or sets, but
  not during scenes.
