* Getting started
  Gather 'round on your favorite modern device and visit
  http://storychat.herokuapp.com/play

  Everyone should set their name (on the bottom right) to something that
  identifies them, so we can keep track of who's around. If you want to chat,
  switch your input type to "ooc" and type away.
** Tokens
   Every player starts off with 10 tokens. Tokens can be spent on buying
   characters, adding details to characters, purchasing outfits and props, and
   adding details to sets.

   They can also be used (through auction) to buy the privilege to frame the next
   scene.
** Picking characters
   In addition to the initial tokens, every player gets a blank character, and
   the ability to customize it as they see fit. The player can refer to existing
   characters when designing this one, but the result will be a new character,
   owned by this player. Players may choose to spend any number of tokens on
   further character customization, according to the rules below.
** Anatomy of a character
   A character is composed of four parts: A name, a description, a costume, and
   a list of held props.
*** Name
    A character name should be brief and only one or two relatively short
    words. For characters whose real name is much longer or composed of more
    words, choose a concise nickname that will be used to refer to them, and
    only use the full name in dialogue when the character introduces itself.

    For example, "Ash" is a nice name.
*** Description
    The character description is the first paragraph in each character's
    description box (all character details are in a single place for now). A
    description is composed of a basic description and zero or
    more *details*. A *detail* decribes, with one or two adjectives, a concrete
    part of the character.

    For example, a description might read like: "Ash is a short and stocky
    person. Ash has long, curly red hair and a nice, friendly smile."

    This description includes the base description and two *details*. 'Ash is a
    short and stocky person.' is the base. 'long, curly red hair' is one
    detail, and 'a nice, friendly smile' is the second.
*** Costume
    The costume is what the character is currently wearing. The costume
    description is the second paragraph in the character description area.

    Costumes are entities, just like characters themselves, which are
    associated with the character as what they are 'wearing'. Much like a
    character's first paragraph, the description for a costume includes a base
    description, and zero or more *details*. The costume section is prefixed by
    '<character> is wearing...'

    For example, "Ash is wearing a dusty, worn cowboy outfit. It has
    exceptionally shiny boots.", is a costume description with a base
    description ('a dusty, worn cowboy outfit'), and a single detail
    ('exceptionally shiny boots').
*** Props
    Finally, the third paragraph describes the props the character is
    carrying. It is prefixed by "<X> is carrying...".

    Props, just like characters and outfits, are entities of their own, with
    the usual description rules.

    For example, "Ash is carrying a pair of revolvers and a leather whip."
*** Implementation
    Descriptions, costumes, and props can all be implemented with a generic
    detail mechanic: Each detail added to a game entity includes a detail type
    (an index into the detail meta-table), which includes information about
    what order the details should be rendered in, and info about what template
    to use when actually rendering each detail, as well as "error" messages the
    parser can use when verbs perform actions that act on or change details
    ("hand X my sword" -> "You're not carrying a sword").

    This, I think, covers everything we might want to add details-wise. For
    example, it covers all three of the above, it covers "exits" if we ever
    added them, it covers rooms and containers ("the box has a sword in it.",
    "John, Jane, and Ash are in the bar"). It can do all this by just specifying
    a template (which will render "smart" text), and maybe some helpers.
** Customizing characters
   Players may choose to change or add detail to any of their character's
   attributes. Costs and restrictions are listed below.
*** Name
    Changing a character's name can only be done once, ever, and costs no
    tokens. The standard restrictions for names apply (short, only one or two
    words)
*** Description
    The base cost for a detail is two tokens. This cost includes a single
    adjective. The base cost for a second adjective for that detail is another
    two tokens.

    Adding a detail to a character requires the base cost of tokens, multiplied
    by the number of details the character already has. Remember that a detail
    is the thing/attribute itself, not the adjectives attached to it, so "a
    warm, loving heart" is a single detail with two adjectives. Second
    adjectives always cost two tokens, regardless of how many details a
    description already has.

    An entire detail can be removed for 1 token. Adjectives cannot be removed
    from existing details.

    A character must have at least one detail at all times. A character can't
    have more than 5 details.
*** Costumes
    A new costume costs 3 tokens + the cost of any details attached to it.

    Detail purchase rules for costumes are the same as for character
    descriptions: 2 token base cost for each detail, with an additional
    adjective costing 2 more tokens, and new token purchase costing the base
    cost multiplied by the number of existing details.

    Unlike character descriptions, costumes can have just a name/identifier
    attached to them, and do not require any details. For example, "A cowboy
    outfit." would cost only 3 tokens to buy.

    Like descriptions, a costume cannot have more than 5 details.
*** Props
    A new prop costs 1 token + the cost of any details attached to it.

    Prop detail purchase rules are identical to costume detail rules.
** New main characters
   New characters have a base cost of 5 tokens for the initial creation of a
   character.

   Additionally, they require a valid description (minimum cost of 2
   tokens), and a costume (minimum cost 3 tokens).

   So, the minimum cost for a brand-new character is 10 tokens.
** Extras
   Extras are a special kind of character. They are meant as minor/side
   characters, and come with some restrictions.

   * They can only speak once per scene
   * They can only take two actions per scene
   * They cannot be customized (name, description, and costume cannot change)
   * They cannot have props
   * Only one detail in their description
   * Only one (optional) detail allowed in their costume

   In exchange for all this, an extra costs a mere 2 tokens to create. An extra
   can be upgraded at any time to a main character for 10 tokens, and keeps all
   its attributes from its days as an extra, but loses all its extra
   restrictions. Extras also have the unique ability that they can be created
   mid-scene.
** Character versioning
   Multiple versions of the same character can exist, tagged with a label for
   future reference. Characters themselves are immutable, but multiple versions
   can be associated with each other and tagged as character descriptions are
   changed. All character versions are preserved in that character's version
   history. Scenes preserve a direct pointer to the version of the character
   that was used for that particular scene.

   Versions themselves don't cost anything, but are created incidentally as
   part of the character customization process.
** Sets
   A set is a location, made up of a name and a description. Sets are where the
   action takes place.

   New sets have a base cost of 10 tokens, which includes a single
   detail. Additional details follow the character detail purchase rules.
* Playing a Scene
** The Lobby
   The Lobby is the invitation to play. One player starts a game session by
   clicking the Play button and choosing "host". This drops the player into a
   lobby where they can configure the scene with various options. Only the host
   can actually change most of these options, but all present players may
   discuss them so the host changes them. The options are listed at the bottom
   of this section.

   The lobby also contains a chatroom for players, and a list of present
   players. The host may kick or ban any players in the lobby.

   In the lobby, players should discuss what the scene should be about.
*** Open/closed/spectator scene
    An open scene will show up on the games list for anyone to join. A closed
    scene can only be joined through a direct invite by the host. A spectator
    scene can be spectated by anyone, but only people who were invited can
    actually participate (note that anyone invited to the scene can choose to
    spectate instead of play).
*** Player limit
    Number of players the scene will be limited to. Must be between 1 and 8
    (TODO: figure out a good limit for the medium. Readability is important)
*** Description
    The description that will appear in the lobby for what the purpose of the
    scene is.
*** Set
    The set is the location for the scene. This cannot change during the scene,
    and is used in the initial framing. The list of available sets is based on
    the sets controlled by all players in the lobby that have set their sets to
    "host can use". The set will automatically frame the scene according to the
    characters and props that are put in it. Characters and props are added by
    players from their own resources. Additional set details like time of day
    are configured by the host.
*** Family-friendly
    Denotes that the scene will be restricted to family-friendly themes and
    language. An FF scene should not have anything sexual, violent,
    drug-related, or any foul language in it. Note that even if a scene is not
    family-friendly, certain themes are completely out of bounds for this
    game. For example, rape (including statutory), violence against child
    characters (in any form, even physical 'discipline' that may be acceptable
    to some groups).

    The FF flag communicates intention. Players will have a chance to change
    whether the final scene is tagged as FF after the scene is complete, but
    will default to this setting.
** Before
   A scene takes place in a single set, and includes a specific set of main
   characters.

   A scene is marked by a slug line -- which is determined by the chosen set +
   time of day. Following the slug line is a scene header, which should be the
   description of the set, with all the details added to it, followed by a brief
   summary of what props are in the set, finalized by what characters are
   present in the scene, along with basic "posing" information for both
   characters and props (John is standing near the entrance, a katana is stuck
   on the ground)
** During
   Once the scene is framed by the heading, players should play out the action
   in the scene until it draws to a close. Players can do anything they want,
   but any player can veto any particular part of the drama at any time, for any
   reason. For rules on vetos, see the Vetoing section.

   Scenes are played out by players using a character to add either dialogue or
   actions. Once the scene draws to a close, players discuss the next step,
   repick characters, etc.
*** Vetoing
    In order to veto, a player should simply push "veto" on an entry. This will
    grey out the entry and all entries that followed it, and mark them as
    "vetoed". At that point, all other players involved can either accept the
    veto, or choose to leave the scene.

    Before placing their final "votes", players should discuss with each other
    why the entry was vetoed, and what can be done instead.

    The player who vetoed an entry can withdraw their veto at any point before
    the vote is finalized, at which point the entry returns to normal and play
    continues as usual.

    If a veto is accepted, the entries are completely removed from the scene,
    and play continues as before, as if the entries had never happened.
** After
*** Awards
    Each player involved in a scene has two tokens to give out: One for the player
    who played their character the best (maybe they led the scene in an excellent
    way, or they really nailed a plot point, or they were excellent supports to a
    central character, or just generally brought life to a scene, regardless of
    their starring status), and one for the player who players themselves enjoyed
    interacting with the most. Maybe they were gracious and patient when something
    wasn't going well, or they helped someone out with a good idea. Tokens cannot
    be given to oneself, and players are not obligated to give away both of their
    tokens if they don't feel anyone was particularly great.

    (Note: In the future, token-giving should be blind and anonymous -- no one
    knows who's received the most tokens, and no one knows who gave tokens to
    whom)

    The player who ends up with the most tokens receives additional tokens equal
    to the total number of players in the scene.

    Finally, the closer the scene was, in length, to the 3-page 'ideal' for a
    scene, the more tokens all players receive.

    A scene that reaches exactly 3 pages (module a couple of actions), is
    granted 5 tokens. The tokens are then scaled according to how far from ideal
    length a scene was, rounded *down*. For example, if the scene was half the
    desired length, or twice the desired length, the token reward is reduced
    from 5 tokens to 2 tokens. If the scene length is higher than 1.8x or lower
    than 0.2x of the ideal, the reward for just playing the scene is reduced to
    1 token.
*** Story arcs
    As scenes are played out, players should organize them into story arcs, in
    whatever order they see fit. These story arcs should tell a larger story
    than what each individual scene does. Scenes in a story arc are ordered
    linearly. There can be multiple story arcs running in parallel, and multiple
    story arcs can use the same scene, if necessary. It's generally helpful to
    have some kind of plan/cohesion to story arcs, and they can be very useful
    in planning future scenes.

    Scenes are only published once they are added to a published story arc.

    Story arcs can also be 'tokened' by players other than the story arc
    manager. Every token given to a story arc is given to the player managing
    that story arc. Any player can token any story arc other than their own, and
    they can token as many as they want.

    A story arc can have multiple managers. In this case, arc tokens are
    awarded by dividing them between all owners when enough tokens have been
    accumulated to divide.
*** Spending tokens
    Tokens can be spent between scenes to add details to characters or sets, but
    not during scenes, with one exception -- extras can be purchased at any point.
